language: python
matrix:
    include:
        - name: "pycalphad release - Python 3.6"
          python: 3.6
          dist: xenial
        - name: "pycalphad release - Python 3.7"
          python: 3.7
          dist: xenial
        - name: "pycalphad release - Python 3.8"
          python: 3.8
          dist: xenial
        - name: "pycalphad develop - Python 3.6"
          python: 3.6
          dist: xenial
          env: PYCALPHAD_DEVELOP=1
        - name: "pycalphad develop - Python 3.7"
          python: 3.7
          dist: xenial
          env: PYCALPHAD_DEVELOP=1
        - name: "pycalphad develop - Python 3.8"
          python: 3.8
          dist: xenial
          env: PYCALPHAD_DEVELOP=1

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n espei-env python=$TRAVIS_PYTHON_VERSION
  - source activate espei-env
  - conda install -c conda-forge -c pycalphad 'pycalphad>=0.8.2' numpy scipy 'sympy' six 'dask>=2' 'distributed>=2' 'tinydb>=3.8' scikit-learn 'emcee<3' pyyaml cerberus bibtexparser sphinx sphinx_rtd_theme pytest nose mock twine 'cyipopt>=0.1.9=*_1002'
  # If pycalphad develop is defined, uninstall the release and install the development version from github
  - if [[ $PYCALPHAD_DEVELOP ]]; then conda remove --force --yes pycalphad; fi
  - if [[ $PYCALPHAD_DEVELOP ]]; then git clone https://github.com/pycalphad/pycalphad pycalphad-dev; fi
  - if [[ $PYCALPHAD_DEVELOP ]]; then cd pycalphad-dev; fi
  - if [[ $PYCALPHAD_DEVELOP ]]; then pip install -e . ; fi
  - if [[ $PYCALPHAD_DEVELOP ]]; then cd .. ; fi

before_script:
  - source activate espei-env
  - pip install -e '.[dev]'
  - echo '!!! Installed packages'
  - conda list
  - echo '!!! Local directory'
  - ls -lh
  # Configure matplotlib to use the agg backend to prevent issues on py27
  - "echo 'backend : Agg' > matplotlibrc"
script:
  - pytest -v --doctest-modules espei tests
notifications:
  email: False
