channels:
  - conda-forge
dependencies:
  - cerberus
  - corner
  - dask>=2
  - distributed>=2
  - emcee<3
  - matplotlib-base
  - numpy
  - pycalphad>=0.8.4,<0.9
  - python-symengine
  - pyyaml
  - scikit-learn
  - scipy
  - sympy>=1.5.1
  - tinydb>=4
  # Developer dependencies
  # Tests
  - pytest
  # PyPI
  - twine
  # Documentation
  - furo
  - ipython  # for pygments syntax highlighting
  - sphinx
